### ISSUE TITLE
six in py3 is failing

### ISSUE THREAD

**Issue by mvmocanu** [pbs/django-atris#2]
While running the `populate_initial_history` command I got this error:

```
django-admin populate_initial_history 
Traceback (most recent call last):
  File "/deployed/bin/django-admin", line 11, in <module>
    sys.exit(execute_from_command_line())
  File "/deployed/lib/python3.4/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/deployed/lib/python3.4/site-packages/django/core/management/__init__.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/deployed/lib/python3.4/site-packages/django/core/management/__init__.py", line 190, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/deployed/lib/python3.4/site-packages/django/core/management/__init__.py", line 40, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "/deployed/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/deployed/lib/python3.4/site-packages/atris/management/commands/populate_initial_history.py", line 5, in <module>
    str = str if six.PY2 else str
NameError: name 'six' is not defined

```

I am using py3, and six is not available in py3.

**Comment by bogdanpop** [comment]
This was fixed in 0.1.9.
